import Head from 'next/head'
import styles from './Page.module.css'
import Content from '@Components/Content/Content';

function Page(props) {
  return (
    <div className={styles.page}>
      <Head>
        <title>Antony Sanchez</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Content>
        {props.children}
      </Content>
    </div>
  )
}

export default Page;