import Head from 'next/head'
import styles from '@Frontend/styles/Home.module.css'
//import Image from 'next/image'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.maincontainer}>
        <div className={styles.container} style={{"float": "left"}}>
          <div className={styles.card}>
            <p className={styles.header}>
              CONNECT antonysanchez.com
            </p>
            <p>
              Antony % Portfolio
            </p>
            <p>
              This portfolio website uses the VT323 font-family, which is Licensed under the Open Font License, and is styled after the VT320 1987 computer terminal. It&apos;s optimized for a desktop experience. The drop down display may not properly work on mobile, alongside some of the other more finnicky code, until further optimization has been done on the web-page. Currently, the website&apos;s index file is under 10 KB in size and will likely not go over 1 MB in total size with further modification. The website uses HTML, Javascript, CSS, and was built with code written by me in Visual Studio 2019.
            </p>
            <p>
              The basic text color is set to &apos;forestgreen&apos;, while the highlighted outlines are set to &apos;darkseagreen&apos; when on-hover. The dropdown makes use of nested menus and &apos;nth-child&apos; CSS pseudo-elements to work with visibility.
            </p>
            <p>
              Antony % Portfolio
            </p>
          </div>
          <div className={styles.card}>
            <p className={styles.header}>
              CD: ./Antony/Portfolio/
            </p>
            <p>
              Antony % Portfolio
            </p>
            <ul>
              <li>
                <a href="subpages/About.html"  target="rightcont">About</a>
              </li>
              <li>
                <a href="subpages/Projects.html" target="rightcont">Projects</a>
              </li>
              <li>
                <a href="subpages/Designs.html" target="rightcont">Designwork</a>
              </li>
              <li>
                <a href="subpages/Website.html" target="rightcont">Website</a>
              </li>
            </ul>
            <p>
              Antony % Portfolio
            </p>
          </div>
        </div>
        <div className={styles.container} style={{"float": "left"}}>
          <div className={styles.card}>
            <p className={styles.header} style={{"margin-bottom": "0px"}}>
              CD: ./Antony/Portfolio/
            </p>
            <div id={styles.rightframe} name="rightcont">
              test
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
